import java.util.Random;
class SharedData {
    int num;
    boolean valueSet = false;
}
class Producer extends Thread {
    SharedData data;
    Random rand = new Random();
    Producer(SharedData data) {
        this.data = data;
    }
    public void run() {
        for (int i = 0; i < 10; i++) {
            synchronized (data) {
                while (data.valueSet) {
                    try {
                        data.wait();
                    } catch (InterruptedException e) {
                        System.out.println(e);
                    }
                }
                data.num = rand.nextInt(100) + 1;
                System.out.println("Number generated by Producer: " + data.num);
                data.valueSet = true;
                data.notify();
            }
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                System.out.println(e);
            }
        }
    }
}
class Consumer extends Thread {
    SharedData data;
    int evenCount = 0;
    Consumer(SharedData data) {
        this.data = data;
    }
    public void run() {
        for (int i = 0; i < 10; i++) {
            synchronized (data) {
                while (!data.valueSet) {
                    try {
                        data.wait();
                    } catch (InterruptedException e) {
                        System.out.println(e);
                    }
                }
                if (data.num % 2 == 0) {
                    evenCount++;
                }
                data.valueSet = false;
                data.notify();
            }
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                System.out.println(e);
            }
        }
        System.out.println("Number even numbers received by Consumer: " + evenCount);
    }
}
public class DriverTwelve {
    public static void main(String[] args) {
        SharedData data = new SharedData();
        Producer p = new Producer(data);
        Consumer c = new Consumer(data);
        p.start();
        c.start();
        try {
            p.join();
            c.join();
        } catch (InterruptedException e) {
            System.out.println(e);
        }
    }
}